FROM ubuntu:noble AS build

ARG NOVNC_VERSION="1.6.0"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && mkdir -p BUILD && \
    apt -y install build-essential debhelper devscripts dpkg-dev fakeroot git sharutils wget

RUN wget --no-check-certificate -qO- https://github.com/novnc/noVNC/archive/refs/tags/v$NOVNC_VERSION.tar.gz | tar -xvz -C /

RUN cd /noVNC-$NOVNC_VERSION && mv app core utils vendor vnc.html vnc_lite.html ../BUILD
COPY /debian /BUILD/debian
RUN cp /noVNC-$NOVNC_VERSION/README.md /BUILD/debian/README.debian
COPY /patch /BUILD/
RUN cd /BUILD/ && debuild -us -uc -b
RUN find / -name "*.deb" -maxdepth 1 -type f -print

FROM scratch
COPY --from=build /*.deb /
